version: '3.5'

services:
  jukebox:
    image: mhzawadi/subsonic_jukebox
    restart: always
    environment:
      - SUB_URL=jukebox:85
      - SUB_ADDR=192.168.1.1
      - SUB_USER=test
      - SUB_PASS=26719a1196d2a940705a59634eb18eab
      - SUB_SALT=c19b2d
    ports:
      - 85:80
